# Generated by Django 6.0.6 on 2026-06-20 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Design', 'Design'), ('Data Scraping', 'Data Scraping'), ('Research', 'Research'), ('Data Entry', 'Data Entry'), ('Automation', 'Automation'), ('AI', 'AI'), ('Web Development', 'Web Development'), ('Video', 'Video'), ('Training & Education', 'Training & Education')], max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('cover_ratio', models.CharField(choices=[('1/1', 'Square (1:1)'), ('4/3', 'Standard (4:3)'), ('3/2', 'Photo (3:2)'), ('16/9', 'Widescreen (16:9)'), ('21/9', 'Ultra Wide (21:9)'), ('4/5', 'Portrait (4:5)'), ('9/16', 'Vertical (9:16)'), ('1.91/1', 'Social Banner (1.91:1)'), ('1/1.414', 'A4 Document')], default='16:9', help_text='Select the layout type (e.g., 16:9 for videos, 1:1 for logos)', max_length=20)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(upload_to='portfolio/covers/')),
                ('live_url', models.URLField(blank=True)),
                ('publication_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.portfoliocategory')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='portfolio/images/')),
                ('video', models.FileField(blank=True, upload_to='portfolio/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('aspect_ratio', models.CharField(choices=[('1/1', 'Square (1:1)'), ('4/3', 'Standard (4:3)'), ('3/2', 'Photo (3:2)'), ('16/9', 'Widescreen (16:9)'), ('21/9', 'Ultra Wide (21:9)'), ('4/5', 'Portrait (4:5)'), ('9/16', 'Vertical (9:16)'), ('1.91/1', 'Social Banner (1.91:1)'), ('1/1.414', 'A4 Document')], default='16:9', help_text='Select the layout type (e.g., 16:9 for videos, 1:1 for logos)', max_length=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.portfolioitem')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.portfoliocategory')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.portfoliosubcategory'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.portfoliocategory')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.portfoliosubcategory')),
            ],
        ),
    ]
