# Generated by Django 6.0.6 on 2026-07-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: Final Website, Source Code, Documentation', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='deliveries/%Y/%m/')),
                ('visible_to_client', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.order')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
