# Generated by Django 6.0.6 on 2026-07-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_paddle_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliocategory',
            name='icon',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
