# Generated by Django 6.0.6 on 2026-08-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_portfoliocategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Project requirements provided by the client.'),
        ),
    ]
