# Generated by Django 6.0.6 on 2026-09-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_paddle_transaction_id_order_easypay_order_ref_and_more'),
    ]

    operations = [
    ]
