# Generated by Django 6.0.6 on 2026-09-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orderattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='easypay_order_ref',
        ),
    ]
