# Generated by Django 6.0.6 on 2026-09-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_phone_number_orderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3),
        ),
    ]
