# Generated by Django 6.0.6 on 2026-09-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_order_currency_orderattachment"),
    ]

    operations = []
