# Generated by Django 6.0.6 on 2026-09-21 06:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260913_2137'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
        migrations.CreateModel(
            name='SaaSInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('daily_limit', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3)),
                ('billing_period_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaaSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_limit', models.PositiveIntegerField(help_text='Maximum number of operations allowed per day.', validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3)),
                ('billing_period_days', models.PositiveIntegerField(default=30, help_text='Number of days this plan remains active.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product', 'sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='SaaSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('free_daily_limit', models.PositiveIntegerField(default=5, help_text='Daily usage limit for free users.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaaSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('daily_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PKR', 'PKR')], default='USD', max_length=3)),
                ('billing_period_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaaSUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(blank=True, default='', help_text='Used to track anonymous users.', max_length=255)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='projectusage',
            name='unique_daily_project_usage',
        ),
        migrations.DeleteModel(
            name='ProjectUsage',
        ),
        migrations.DeleteModel(
            name='ProjectUsageSettings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan',
        ),
        migrations.AddField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.order'),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saasplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.saasproduct'),
        ),
        migrations.AddField(
            model_name='saassubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.saasplan'),
        ),
        migrations.AddField(
            model_name='saassubscription',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.saasproduct'),
        ),
        migrations.AddField(
            model_name='saassubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saasinvoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.saassubscription'),
        ),
        migrations.AddField(
            model_name='saasusage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='core.saasproduct'),
        ),
        migrations.AddField(
            model_name='saasusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saas_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='saasplan',
            index=models.Index(fields=['product', 'is_active'], name='core_saaspl_product_e54db2_idx'),
        ),
        migrations.AddConstraint(
            model_name='saasplan',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='unique_saas_plan_name_per_product'),
        ),
        migrations.AddIndex(
            model_name='saassubscription',
            index=models.Index(fields=['user', 'product', 'status'], name='core_saassu_user_id_abe10a_idx'),
        ),
        migrations.AddIndex(
            model_name='saassubscription',
            index=models.Index(fields=['end_date', 'status'], name='core_saassu_end_dat_e376d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='saassubscription',
            constraint=models.CheckConstraint(condition=models.Q(('daily_limit__gt', 0)), name='saas_subscription_daily_limit_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='saassubscription',
            constraint=models.CheckConstraint(condition=models.Q(('billing_period_days__gt', 0)), name='saas_subscription_billing_days_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='saassubscription',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='saas_subscription_price_gte_zero'),
        ),
        migrations.AddIndex(
            model_name='saasusage',
            index=models.Index(fields=['user', 'product', 'date'], name='core_saasus_user_id_35907d_idx'),
        ),
        migrations.AddIndex(
            model_name='saasusage',
            index=models.Index(fields=['identity_key', 'product', 'date'], name='core_saasus_identit_5299a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='saasusage',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 0)), name='saas_usage_count_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='saasusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('identity_key', ''), ('user__isnull', False)), models.Q(('identity_key__gt', ''), ('user__isnull', True)), _connector='OR'), name='saas_usage_user_or_anonymous'),
        ),
        migrations.AddConstraint(
            model_name='saasusage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product', 'date'), name='unique_daily_user_product_usage'),
        ),
        migrations.AddConstraint(
            model_name='saasusage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('identity_key', 'product', 'date'), name='unique_daily_anonymous_product_usage'),
        ),
    ]
