# Generated by Django 6.0.6 on 2026-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orderattachment_saasinvoice_saasplan_saasproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saasproduct',
            name='usage_unit',
            field=models.CharField(default='uses', help_text='Unit shown to users, e.g. images, searches, requests.', max_length=50),
        ),
    ]
